let users = [
  {
    "roll": "User",
    "password": '11111111',
    "language": "en",
    "status": "Approved",
    "firstname": "Masoon",
    "lastname": "User",
    "email": "masoonuser@gmail.com",
    "phone_number": "+966546060960"
  }, {
    "roll": "Admin",
    "password": '11111111',
    "language": "en",
    "status": "Pending",
    "firstname": "Taymoor",
    "lastname": "Akbar",
    "email": "masoonapp@gmail.com",
    "phone_number": "11111111"
  }, {
    "roll": "Publisher",
    "password": '11111111',
    "language": "en",
    "status": "Approved",
    "firstname": "Advertiser",
    "lastname": "One",
    "email": "masoonadv@gmail.com",
    "phone_number": "+96678747744"
  }, {
    "roll": "Publisher",
    "password": '11111111',
    "language": "en",
    "status": "Pending",
    "firstname": "Taymoor",
    "lastname": "Akbar",
    "email": "taimoorak3@gmail.com",
    "phone_number": "+966734289723"
  }, {
    "roll": "Admin",
    "password": '11111111',
    "language": "en",
    "status": "Approved",
    "firstname": "Taymoor",
    "lastname": "Akbar",
    "email": "abdullahgulyani@gmail.com",
    "phone_number": "11111111"
  }, {
    "roll": "Publisher",
    "password": '11111111',
    "language": "en",
    "status": "Approved",
    "firstname": "Advertiser",
    "lastname": "two",
    "email": "advertisertwo@gmail.com",
    "phone_number": "+9664545464654"
  }, {
    "roll": "Publisher",
    "password": '11111111',
    "language": "en",
    "status": "Approved",
    "firstname": "Abubakar",
    "lastname": "Ahmed",
    "email": "wdv63829@zwoho.com",
    "phone_number": "+966173972197321"
  }, {
    "roll": "Publisher",
    "password": '11111111',
    "language": "ar",
    "status": "Approved",
    "firstname": "django",
    "lastname": "rest",
    "email": "gta09074@cuoly.com",
    "phone_number": "+96632742372384"
  }, {
    "roll": "Publisher",
    "password": '11111111',
    "language": "en",
    "status": "Approved",
    "firstname": "Tom",
    "lastname": "Hanks",
    "email": "crz22957@cuoly.com",
    "phone_number": "+966312126127312"
  }, {
    "roll": "Publisher",
    "password": '11111111',
    "language": "en",
    "status": "Approved",
    "firstname": "Jack",
    "lastname": "Harber",
    "email": "xfq35897@cuoly.com",
    "phone_number": "+966237947293734"
  }, {
    "roll": "Publisher",
    "password": '11111111',
    "language": "en",
    "status": "Approved",
    "firstname": "Mark",
    "lastname": "Johnson",
    "email": "nhi58162@cuoly.com",
    "phone_number": "+966329749237327"
  }, {
    "roll": "Publisher",
    "password": '11111111',
    "language": "en",
    "status": "Approved",
    "firstname": "Hilal",
    "lastname": "Company",
    "email": "yru49197@eoopy.com",
    "phone_number": "+9663321334241"
  }, {
    "roll": "Publisher",
    "password": '11111111',
    "language": "en",
    "status": "Approved",
    "firstname": "Taymoor",
    "lastname": "Akbar",
    "email": "taymoor@gmail.com",
    "phone_number": "+9663232323232"
  }, {
    "roll": "Publisher",
    "password": '11111111',
    "language": "ar",
    "status": "Approved",
    "firstname": "Taymoor",
    "lastname": "Akbar",
    "email": "taymoorakbar12121@outlook.com",
    "phone_number": "+9663328410304"
  }, {
    "roll": "Publisher",
    "password": '11111111',
    "language": "en",
    "status": "Approved",
    "firstname": "Kaleen",
    "lastname": "Bhai",
    "email": "kaleenbhai@gmail.com",
    "phone_number": "+9664343543443"
  }, {
    "roll": "User",
    "password": '11111111',
    "language": "en",
    "status": "Approved",
    "firstname": "Uzair",
    "lastname": "Ali",
    "email": "uzairalimurtaz1a@gmail.com",
    "phone_number": "+966333111999"
  }, {
    "roll": "User",
    "password": '11111111',
    "language": "en",
    "status": "Approved",
    "firstname": "John",
    "lastname": "Doe",
    "email": "john@gmail.com",
    "phone_number": "+966233566877"
  }, {
    "roll": "User",
    "password": '11111111',
    "language": "en",
    "status": "Approved",
    "firstname": "Ehsan",
    "lastname": "Ul",
    "email": "ehsanulhaq0027@gmail.com"
  }, {
    "roll": "User",
    "password": '11111111',
    "language": "ar",
    "status": "Approved",
    "firstname": "Kamran",
    "lastname": "Ali",
    "email": "alik11590@gmail.com"
  }, {
    "roll": "User",
    "password": '11111111',
    "language": "en",
    "status": "Approved",
    "firstname": "Muhammad",
    "lastname": "Abdullah",
    "email": "m.abdullah@gmail.com",
    "phone_number": "+966555555454"
  }, {
    "roll": "User",
    "password": '11111111',
    "language": "en",
    "status": "Approved",
    "firstname": "Uzair",
    "lastname": "Ali",
    "email": "uzairalimurtaza@gmail.com"
  }, {
    "roll": "User",
    "password": '11111111',
    "language": "en",
    "status": "Approved",
    "firstname": "Kamran",
    "lastname": "Ghafoor",
    "email": "i.kamranghafoor45@gmail.com"
  }, {
    "roll": "User",
    "password": '11111111',
    "language": "en",
    "status": "Approved",
    "firstname": "Kamran",
    "lastname": "Ghafoor",
    "email": "kamranghafoor6@gmail.com"
  }, {
    "roll": "User",
    "password": '11111111',
    "language": "ar",
    "status": "Approved",
    "firstname": "Jos",
    "lastname": "Buttler",
    "email": "buttler@gmail.com",
    "phone_number": "+966234567891"
  }, {
    "roll": "User",
    "password": '11111111',
    "language": "ar",
    "status": "Approved",
    "firstname": "Kamran",
    "lastname": "Haider",
    "email": "kamran@gmail.com",
    "phone_number": "+966234112341"
  }, {
    "roll": "Publisher",
    "password": '11111111',
    "language": "ar",
    "status": "Approved",
    "firstname": "Taymoor",
    "lastname": "Akbar",
    "email": "taimoorak4@gmail.com",
    "phone_number": "+923328410304"
  }, {
    "roll": "User",
    "password": '11111111',
    "language": "en",
    "status": "Approved",
    "firstname": "Taymoor",
    "lastname": "Akbar",
    "email": "taymur.akbar11@gmail.com"
  }, {
    "roll": "User",
    "password": '11111111',
    "language": "en",
    "status": "Approved",
    "firstname": "Taymoor",
    "lastname": "Akbar",
    "email": "taymoorakbar@outlook.com",
    "phone_number": "+966111111111"
  }, {
    "roll": "User",
    "password": '11111111',
    "language": "en",
    "status": "Pending",
    "firstname": "Taimoor",
    "lastname": "Akbar",
    "email": "taymur.akbar1@gmail.com",
    "phone_number": "+966555555555"
  }, {
    "roll": "User",
    "password": '11111111',
    "language": "en",
    "status": "Approved",
    "firstname": "Uzair",
    "lastname": "Ali",
    "email": "uzairali@gmail.com",
    "phone_number": "+966231455651"
  }]

module.exports = users